// Disposable local tests. Build first; no production credentials or network used.
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const ts=(await import(path.join(root,'node_modules/typescript/lib/typescript.js'))).default;
function module(file,replace={}){let source=fs.readFileSync(path.join(root,file),'utf8');for(const [a,b]of Object.entries(replace))source=source.replaceAll(a,b);return 'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64')}
const socialURL=module('lib/social.ts'),social=await import(socialURL),report=await import(module('lib/metrics-report.ts',{"'./social'":JSON.stringify(socialURL)})),zip=await import(module('lib/backup-zip.ts'));
let checks=0;function check(value,expected){assert.deepEqual(value,expected);checks++}
check(report.parseReportCSV('\uFEFFPost URL,Views,Notes\r\nhttps://youtu.be/abcdefghijk,"1,234","One\nTwo"\r\n').at(1),['https://youtu.be/abcdefghijk','1,234','One\nTwo']);
check(report.parseMetricCell('1,234','views','YouTube'),1234);check(report.parseMetricCell('','views','YouTube'),null);assert.throws(()=>report.parseMetricCell('1.2K','views','YouTube'));checks++;
check(report.guessColumn(['Video URL','Views'],'post'),0);check(social.metricValue({metricsSource:'import',views:99,syncedMetrics:{likes:0}},'views'),null);check(social.metricValue({metricsSource:'import',syncedMetrics:{likes:0}},'likes'),0);
check(social.reportBasis({metricsSource:'import',metricsPeriod:'Imported reporting period: 2026-09-01 to 2026-09-30'}),'Period 2026-09-01 to 2026-09-30');
const fileBlob=new Blob(['A real file\n']),hash=await zip.sha256(fileBlob),manifest={product:'Client Dashboard',backupVersion:1,records:[],files:[{id:'file-one',size:fileBlob.size,sha256:hash}]};
const archive=await zip.backupZip([{name:'manifest.json',data:new Blob([JSON.stringify(manifest)])},{name:'files/file-one',data:fileBlob}]),reader=await zip.readBackupZip(archive);check(reader.manifest,manifest);check(await (await reader.entry('files/file-one')).text(),'A real file\n');
const corrupt=new Uint8Array(await archive.arrayBuffer());const at=Buffer.from(corrupt).indexOf('A real file');corrupt[at]=66;const damaged=await zip.readBackupZip(new Blob([corrupt]));await assert.rejects(()=>damaged.entry('files/file-one'),/checksum/);checks++;
const packages=path.join(root,'node_modules/.pnpm');const pkg=fs.readdirSync(packages).find(x=>x.startsWith('miniflare@'));if(!pkg)throw Error('Miniflare is missing. Install dependencies with pnpm.');
const {Miniflare,createFetchMock}=await import(path.join(packages,pkg,'node_modules/miniflare/dist/src/index.js'));
const server=path.join(root,'dist/server'),files=fs.readdirSync(server,{recursive:true}).filter(f=>/\.(js|mjs)$/.test(f)),modules=['index.js',...files.filter(f=>f!=='index.js')].map(f=>({type:'ESModule',path:path.join(server,f)}));
const password=crypto.randomUUID(),headers={Authorization:'Basic '+Buffer.from('owner:'+password).toString('base64'),'Content-Type':'application/json'},fetchMock=createFetchMock();fetchMock.disableNetConnect();
function worker(){return new Miniflare({name:'client-dashboard-personal',modules,modulesRoot:server,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],bindings:{DASHBOARD_USERNAME:'owner',DASHBOARD_PASSWORD:password},d1Databases:{DB:'00000000-0000-4000-8000-000000000000'},r2Buckets:['BUCKET'],assets:{directory:path.join(root,'dist/client'),binding:'ASSETS',routerConfig:{has_user_worker:true,invoke_user_worker_ahead_of_assets:true}},fetchMock})}
const mf=worker(),target=worker();
const call=(route,body,method='POST',instance=mf,extra={})=>instance.dispatchFetch('https://test.local'+route,{method,headers:{...headers,...extra},...(body?{body:JSON.stringify(body)}:{}),redirect:'manual'});
async function ok(route,body,method='POST',instance=mf){const r=await call(route,body,method,instance);assert.equal(r.status,200,route+': '+await r.clone().text());checks++;return r.json()}
async function stored(db,id){const row=await db.prepare('SELECT payload FROM records WHERE id=?').bind(id).first();return row?JSON.parse(row.payload):null}
try{
const db=await mf.getD1Database('DB'),dest=await target.getD1Database('DB'),bucket=await mf.getR2Bucket('BUCKET'),destBucket=await target.getR2Bucket('BUCKET');
for(const d of [db,dest]){await d.prepare('CREATE TABLE records (id TEXT PRIMARY KEY,kind TEXT,client TEXT,payload TEXT)').run();await d.prepare("INSERT INTO records VALUES ('initialized','meta','','{}')").run()}
for(const route of ['/api/recovery','/api/trash','/api/metrics/import','/api/recovery/files']){check((await mf.dispatchFetch('https://test.local'+route,{method:'POST',body:'{}'})).status,401);check((await call(route,{},'POST',mf,{Origin:'https://evil.test'})).status,403)}
for(const id of ['client-a','client-b'])await ok('/api/business',{id,client:id,kind:'client',name:id});
const project={id:'project-1',kind:'project',client:'client-a',title:'Moved project',status:'Planning',date:'2026-10-10',budget:100,currency:'PHP',owner:'',notes:''};await ok('/api/business',project);await ok('/api/business',{...project,client:'client-b'});check((await db.prepare('SELECT client FROM records WHERE id=?').bind(project.id).first()).client,'client-b');
const task={id:'task-1',kind:'task',client:'client-b',title:'Task',status:'To do',date:'2026-10-10',priority:'Normal',owner:'',projectId:project.id,contentId:'',notes:''};await ok('/api/business',task);check((await call('/api/business',{...project,client:'client-a'})).status,400);await ok('/api/business',{...task,projectId:'',client:'client-a'});check((await db.prepare('SELECT client FROM records WHERE id=?').bind(task.id).first()).client,'client-a');
const invoice={id:'invoice-1',kind:'invoice',client:'client-a',title:'Invoice',date:'2026-10-20',issuedDate:'2026-10-01',amount:100,paid:0,currency:'PHP',status:'Draft',projectId:'',notes:''};await ok('/api/business',invoice);await ok('/api/business',{...invoice,client:'client-b'});check((await db.prepare('SELECT client FROM records WHERE id=?').bind(invoice.id).first()).client,'client-b');
// Repair an old indexed-client mismatch using the shipped migration.
await db.prepare("UPDATE records SET client='client-a' WHERE id=?").bind(project.id).run();await db.prepare(fs.readFileSync(path.join(root,'drizzle/0001_repair_client_references.sql'),'utf8')).run();check((await db.prepare('SELECT client FROM records WHERE id=?').bind(project.id).first()).client,'client-b');check((await db.prepare("SELECT client FROM records WHERE id='initialized'").first()).client,'');
const account={id:'social-'+crypto.randomUUID(),kind:'social-account',client:'client-a',name:'Channel',platform:'YouTube',url:'',externalId:'',apiVersion:''};await ok('/api/social-accounts',account);
const content={id:'post-1',kind:'content',client:'client-a',title:'Post',format:'Short-form',platform:'YouTube',status:'Published',date:'2026-10-03',owner:'',notes:'',resourceIds:[],views:0,likes:0,comments:0,shares:0,clicks:0,socialAccountId:account.id,postRef:'https://youtu.be/abcdefghijk'};await ok('/api/records',content);
const reportBody={accountId:account.id,filename:'export.csv',basis:'Selected reporting period',start:'2026-09-01',end:'2026-09-30',rows:[{contentId:content.id,ref:'abcdefghijk',metrics:{views:1234,likes:0}}]};await ok('/api/metrics/import',reportBody);check((await stored(db,content.id)).syncedMetrics,{views:1234,likes:0});check((await call('/api/metrics/import',{...reportBody,rows:[...reportBody.rows,...reportBody.rows]})).status,409);check((await call('/api/metrics/import',{...reportBody,rows:[{...reportBody.rows[0],contentId:'wrong-post'}]})).status,409);
const bAccount={...account,id:'social-'+crypto.randomUUID(),client:'client-b'};await ok('/api/social-accounts',bAccount);check((await call('/api/metrics/import',{...reportBody,accountId:bAccount.id})).status,409);
await ok('/api/records',{...content,title:'New title'});check((await stored(db,content.id)).metricsSource,'import');check((await stored(db,content.id)).metricsImportFile,'export.csv');
await ok('/api/records',{...content,postRef:'https://youtu.be/12345678901'});check((await stored(db,content.id)).syncedMetrics,{});await ok('/api/records',content);await ok('/api/metrics/import',reportBody);
await ok('/api/business',{...task,projectId:'',client:'client-a',contentId:content.id});await ok('/api/records',{id:content.id},'DELETE');check((await stored(db,task.id)).contentId,'');let trash=(await ok('/api/trash',null,'GET')).items;let item=trash.find(t=>t.record.id===content.id);check((await ok('/api/records',null,'GET')).records.some(r=>r.kind==='trash'),false);
await ok('/api/business',{...(await stored(db,task.id)),title:'Edited while post in Trash'});await ok('/api/trash',{id:item.id});check((await stored(db,task.id)).contentId,content.id);check((await stored(db,task.id)).title,'Edited while post in Trash');
const form=new FormData();form.set('client','client-a');form.set('file',new File([fileBlob],'note.txt'));const multipart=new Request('https://test.local/api/files',{method:'POST',body:form});const upload=await mf.dispatchFetch('https://test.local/api/files',{method:'POST',headers:{Authorization:headers.Authorization,'Content-Type':multipart.headers.get('Content-Type')},body:await multipart.arrayBuffer()});check(upload.status,200);const resource=(await upload.json()).record;check(await (await call('/api/files?id='+resource.id,null,'GET')).text(),'A real file\n');
await ok('/api/records',{...(await stored(db,content.id)),resourceIds:[resource.id]});await ok('/api/records',{id:resource.id},'DELETE');check(!!await bucket.head(resource.id),true);check((await stored(db,content.id)).resourceIds,[]);item=(await ok('/api/trash',null,'GET')).items.find(t=>t.record.id===resource.id);await ok('/api/trash',{id:item.id});check((await stored(db,content.id)).resourceIds,[resource.id]);
const backup=await ok('/api/recovery',null,'GET');backup.files=[{id:resource.id,size:fileBlob.size,sha256:hash}];const preview=await ok('/api/recovery',{action:'preview',backup},'POST',target);check(preview.newRecords,backup.records.length);check((await call('/api/recovery',{action:'commit',session:preview.session},'POST',target)).status,409);
const fileURL='/api/recovery/files?'+new URLSearchParams({session:preview.session,id:resource.id});check((await target.dispatchFetch('https://test.local'+fileURL,{method:'PUT',headers,body:new Blob(['Wrong bytes\n'])})).status,400);check((await target.dispatchFetch('https://test.local'+fileURL,{method:'PUT',headers,body:fileBlob})).status,200);await ok('/api/recovery',{action:'commit',session:preview.session},'POST',target);check(await (await call('/api/files?id='+resource.id,null,'GET',target)).text(),'A real file\n');
await ok('/api/business',{...(await stored(dest,task.id)),title:'Keep current work'},'POST',target);const repeated=await ok('/api/recovery',{action:'preview',backup},'POST',target);check(repeated.newRecords,0);await ok('/api/recovery',{action:'commit',session:repeated.session},'POST',target);check((await stored(dest,task.id)).title,'Keep current work');const issued=await ok('/api/business',{...invoice,id:'invoice-new'},'POST',target);check(issued.record.invoiceNumber,'INV-2026-00002');
const invalid=structuredClone(backup);invalid.records.find(r=>r.kind==='task').contentId='missing-post';const conflict=await call('/api/recovery',{action:'preview',backup:invalid});check(conflict.status,200); // Existing records are kept; ignored edits cannot replace them.
await ok('/api/recovery',{session:(await conflict.json()).session},'DELETE');
const wrong=structuredClone(backup);wrong.records.find(r=>r.id===task.id).client='client-b';check((await call('/api/recovery',{action:'preview',backup:wrong})).status,409);
const orphan=structuredClone(backup);orphan.records.push({...task,id:'orphan-task',contentId:'missing'});check((await call('/api/recovery',{action:'preview',backup:orphan})).status,400);
const staged=structuredClone(backup),copyResource={...resource,id:'staged-file',url:'/api/files?id=staged-file'};staged.records.push(copyResource);staged.files.push({id:copyResource.id,size:fileBlob.size,sha256:hash});const stage=await ok('/api/recovery',{action:'preview',backup:staged},'POST',target);check((await target.dispatchFetch('https://test.local/api/recovery/files?'+new URLSearchParams({session:stage.session,id:copyResource.id}),{method:'PUT',headers,body:fileBlob})).status,200);await ok('/api/recovery',{session:stage.session},'DELETE',target);check(await destBucket.head(stage.session+'/'+copyResource.id),null);check(!!await destBucket.head((await stored(dest,resource.id)).storageKey),true);
check((await call('/api/business',{id:'client-a'},'DELETE')).status,400);await ok('/api/business',{id:'empty-client',client:'empty-client',kind:'client',name:'Empty'});await ok('/api/business',{id:'empty-client'},'DELETE');item=(await ok('/api/trash',null,'GET')).items.find(t=>t.record.id==='empty-client');await ok('/api/trash',{id:item.id});
await ok('/api/records',{id:resource.id},'DELETE');item=(await ok('/api/trash',null,'GET')).items.find(t=>t.record.id===resource.id);await ok('/api/trash',{id:item.id},'DELETE');check(await bucket.head(resource.id),null);
const themes=JSON.parse(fs.readFileSync(path.join(root,'lib/theme-catalog.json'),'utf8'));check(themes.length,10);for(const t of themes.filter(t=>t.pattern)){check(fs.existsSync(path.join(root,'public/themes',t.pattern+'.svg')),true)}
console.log(`PASS: ${checks} assertions across migration, reassignment, authentication, CSV imports, Trash, file backup/restore and invoice counters. Disposable D1/R2 only.`);
}finally{await mf.dispose();await target.dispose();await fetchMock.close()}
