import {database} from '@/db/raw';
import {matchReportPost,reportMetrics} from '@/lib/metrics-report';
export async function POST(req:Request){try{
 const input:any=await req.json();if(!input||typeof input.accountId!=='string'||!Array.isArray(input.rows)||!input.rows.length||input.rows.length>500||typeof input.filename!=='string'||input.filename.length>200||!['Lifetime counters','Selected reporting period'].includes(input.basis))return Response.json({error:'Choose an account, report basis and up to 500 matched rows.'},{status:400});
 if(input.basis==='Selected reporting period'&&(!/^\d{4}-\d{2}-\d{2}$/.test(input.start)||!/^\d{4}-\d{2}-\d{2}$/.test(input.end)||input.start>input.end||new Date(input.start+'T12:00:00Z').toISOString().slice(0,10)!==input.start||new Date(input.end+'T12:00:00Z').toISOString().slice(0,10)!==input.end))return Response.json({error:'Choose a valid start and end date.'},{status:400});
 const db=database(),a:any=await db.prepare("SELECT payload FROM records WHERE id=? AND kind='social-account'").bind(input.accountId).first();if(!a)return Response.json({error:'Account not found.'},{status:400});const account=JSON.parse(a.payload),rows=await db.prepare("SELECT id,payload FROM records WHERE kind='content' AND client=?").bind(account.client).all(),records=rows.results.map((x:any)=>JSON.parse(x.payload)),seen=new Set<string>(),writes:any[]=[];
 const updated=[];for(const row of input.rows){const matches=typeof row.ref==='string'&&row.ref.length<=2000?matchReportPost(records,account,row.ref):[];if(matches.length!==1||matches[0].id!==row.contentId||seen.has(row.contentId))return Response.json({error:'A post is unmatched, duplicated, ambiguous or changed since preview. Preview the report again.'},{status:409});const metrics=row.metrics;if(!metrics||typeof metrics!=='object'||Array.isArray(metrics)||!Object.keys(metrics).length||Object.entries(metrics).some(([key,value])=>!reportMetrics.includes(key)||typeof value!=='number'||!Number.isFinite(value)||Math.abs(value)>1e15||value<0&&!(account.platform==='LinkedIn'&&key==='likes')))return Response.json({error:'Use valid numeric counts for supported metrics.'},{status:400});seen.add(row.contentId);const previous=matches[0],record={...previous,metricsSource:'import',syncedMetrics:metrics,metricsSyncedAt:new Date().toISOString(),metricsImportFile:input.filename,metricsPeriod:input.basis==='Lifetime counters'?'Imported lifetime counters':'Imported reporting period: '+input.start+' to '+input.end};delete record.metricsPostId;updated.push(record);writes.push(db.prepare('UPDATE records SET payload=? WHERE id=? AND payload=?').bind(JSON.stringify(record),record.id,JSON.stringify(previous)));}
 const saved:any[]=[];for(let i=0;i<writes.length;i+=50){const result=await db.batch(writes.slice(i,i+50));for(let j=0;j<result.length;j++)if(Number(result[j].meta.changes)>0)saved.push(updated[i+j]);}
 return Response.json({records:saved,conflicts:updated.length-saved.length});
 }catch{return Response.json({error:'Report could not be imported. Check its dates and numbers; retry preview.'},{status:400})}}
