"use client";
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {readPlanWorkbook} from '@/lib/read-xlsx';
import {planColumns,planRow} from '@/lib/calendar-plan';
import {toast} from 'sonner';
export function CalendarImport({client,clientName,month,onImported}:{client:string;clientName:string;month:string;onImported:(rows:any[])=>void}){
 const [open,setOpen]=useState(false),[rows,setRows]=useState<any[]>([]),[errors,setErrors]=useState<string[]>([]),[busy,setBusy]=useState(false),[filename,setFilename]=useState('');
 async function preview(file?:File){setRows([]);setErrors([]);setFilename(file?.name||'');if(!file)return;setBusy(true);try{const table=await readPlanWorkbook(file);const headers=table.find(r=>r.row===1)?.values||[];if(!planColumns.every((h,i)=>headers[i]?.trim()===h))throw Error('Keep the template column headers on row 1 of Plan.');const good:any[]=[],bad:string[]=[];for(const row of table.filter(r=>r.row>1)){const v=row.values;if(!v[1]?.trim())continue;const result=planRow.safeParse({date:v[0],title:v[1],format:v[2],platform:v[3],status:v[4]||'Idea',owner:v[5]||'',campaign:v[6]||'',objective:v[7]||'Awareness',priority:v[8]||'Normal',notes:v[9]||''});if(!result.success)bad.push('Row '+row.row+': '+result.error.issues[0].path.join('.')+' — '+result.error.issues[0].message);else if(!result.data.date.startsWith(month))bad.push('Row '+row.row+': date must be in '+month);else good.push(result.data)}if(!good.length&&!bad.length)bad.push('Add at least one title and publishing date to the Plan sheet.');setRows(good);setErrors(bad)}catch(e){setErrors([(e as Error).message])}finally{setBusy(false)}}
 async function commit(){setBusy(true);try{const res=await fetch('/api/calendar/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client,month,rows})}),data:any=await res.json();if(!res.ok)throw Error(data.error);onImported(data.records);toast.success(data.records.length+' items imported; '+data.skipped+' duplicates skipped.');setOpen(false);setRows([]);setFilename('')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 return <><a className="secondary" href="/downloads/Monthly-Content-Plan-Template.xlsx" download>Excel month template</a><button className="secondary" onClick={()=>{setOpen(true);setRows([]);setErrors([]);setFilename('')}}>Upload monthly plan</button><Dialog open={open} onOpenChange={v=>!busy&&setOpen(v)}><DialogContent className="editor"><DialogTitle>Import monthly content plan</DialogTitle><DialogDescription>Import into {clientName} for {month}. Existing items stay saved. Matching date, title, format and channel combinations are skipped.</DialogDescription><p>Download the Excel template. Set the first day of your month in Instructions!B2, fill in Plan, then save in Excel before uploading. Blank titles are skipped. Add rows for multiple posts in a day.</p><input type="file" accept=".xlsx" aria-label="Upload Excel monthly plan" disabled={busy} onChange={e=>{preview(e.target.files?.[0]);e.target.value=''}}/>{filename&&<p>{filename} · {rows.length} valid rows</p>}{errors.length>0&&<div role="alert" className="import-errors">{errors.map((e,i)=><p key={i}>{e}</p>)}<strong>Fix these rows before importing. Nothing has been saved.</strong></div>}{rows.length>0&&<div className="import-preview"><table><thead><tr><th>Date</th><th>Title</th><th>Channel</th><th>Status</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.date}</td><td>{r.title}</td><td>{r.platform}</td><td>{r.status}</td></tr>)}</tbody></table></div>}<div className="form-actions"><button className="secondary" disabled={busy} onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={busy||!!errors.length||!rows.length} onClick={commit}>{busy?'Processing…':'Import plan'}</button></div></DialogContent></Dialog></>
}
