"use client";
import {useEffect,useState} from 'react';
import {Download,Monitor,Check} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type InstallEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
export function DesktopApp(){
 const [open,setOpen]=useState(false),[prompt,setPrompt]=useState<InstallEvent|null>(null),[installed,setInstalled]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{const media=window.matchMedia('(display-mode: standalone)');const update=()=>setInstalled(media.matches);update();media.addEventListener('change',update);const before=(event:Event)=>{event.preventDefault();setPrompt(event as InstallEvent)};const done=()=>{setInstalled(true);setPrompt(null);setMessage('Installation completed.')};window.addEventListener('beforeinstallprompt',before);window.addEventListener('appinstalled',done);if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js',{scope:'/'}).catch(console.error);return()=>{media.removeEventListener('change',update);window.removeEventListener('beforeinstallprompt',before);window.removeEventListener('appinstalled',done)}},[]);
 async function install(){if(!prompt)return;setBusy(true);try{await prompt.prompt();const result=await prompt.userChoice;setMessage(result.outcome==='accepted'?'Installation accepted. Your browser will finish adding the app.':'Installation was cancelled. You can still download a desktop shortcut.');setPrompt(null)}catch{setMessage('Use your browser’s installation menu to add the dashboard.')}finally{setBusy(false)}}
 return <><button className="desktop-button" onClick={()=>setOpen(true)}><Monitor size={16}/>{installed?'Desktop app':'Desktop access'}</button><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogTitle>Use Client Dashboard on desktop</DialogTitle><DialogDescription>Install the web app or download a shortcut for your computer.</DialogDescription><div className="desktop-guide"><section><h3>{installed?'App window is active':'Install as a desktop app'}</h3>{installed?<p><Check size={16} className="inline"/> You are using the dashboard in its app window.</p>:<><p>Open this dashboard in your desktop browser. If installation is available, use the button below or your browser’s install option.</p>{prompt&&<button className="primary" disabled={busy} onClick={install}><Download size={16}/>{busy?'Installing…':'Install desktop app'}</button>}<p className="subtle">Chrome / Edge: use the install icon in the address bar or the browser menu. Safari on Mac: File → Add to Dock.</p></>}{message&&<p className="install-state" role="status">{message}</p>}</section><section><h3>Download desktop shortcuts</h3><p>Includes a Windows shortcut, a Mac shortcut, and setup instructions. Extract the ZIP, then move the shortcut for your computer to the desktop.</p><a className="secondary" href="/downloads/Client-Dashboard-Desktop.zip" download><Download size={16}/>Download desktop package</a></section><p className="desktop-note">The app and shortcuts open your private online dashboard. Internet access and your personal dashboard sign-in are required to load and save client data.</p></div></DialogContent></Dialog></>
}
