"use client";
import {useEffect,useState} from 'react';
import {toast} from 'sonner';
import {backupZip,readBackupZip,sha256,downloadBlob,backupLimit} from '@/lib/backup-zip';
export function RecoveryWorkspace({onChanged}:{onChanged:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[items,setItems]=useState<any[]>([]),[preview,setPreview]=useState<any>(null),[zip,setZip]=useState<Awaited<ReturnType<typeof readBackupZip>>|null>(null),[confirmed,setConfirmed]=useState(false);
 async function trash(){try{const r=await fetch('/api/trash'),d:any=await r.json();if(!r.ok)throw Error(d.error||'Trash is unavailable');setItems(d.items)}catch(e){setError((e as Error).message)}}useEffect(()=>{trash()},[]);
 async function exportBackup(){setBusy(true);setError('');setMessage('Reading saved records…');try{
  const response=await fetch('/api/recovery'),manifest:any=await response.json();if(!response.ok)throw Error(manifest.error);if(manifest.records.length>2000)throw Error('This workspace exceeds the 2,000-record browser restore limit. Arrange a D1 and R2 backup with your hosting maintainer.');const resources=manifest.records.filter((r:any)=>r.kind==='resource'&&r.type==='File');if(resources.reduce((n:number,r:any)=>n+r.size,0)>backupLimit-8*1024*1024)throw Error('This workspace exceeds the 200 MB browser backup limit. Use the hosting backup process in the owner guide; do not delete files to reduce backup size.');
  const files=[],entries:{name:string;data:Blob}[]=[];for(const [index,r] of resources.entries()){setMessage('Downloading file '+(index+1)+' of '+resources.length+': '+r.name);const response=await fetch('/api/files?id='+encodeURIComponent(r.id));if(!response.ok)throw Error('Could not include '+r.name+'. No partial backup has been downloaded.');const blob=await response.blob();if(blob.size!==r.size)throw Error('Stored file size changed. Reload and retry backup.');files.push({id:r.id,size:blob.size,sha256:await sha256(blob)});entries.push({name:'files/'+r.id,data:blob})}
  const metadata=new Blob([JSON.stringify({...manifest,files})],{type:'application/json'});if(metadata.size>8*1024*1024)throw Error('Records exceed the 8 MB backup manifest limit. Use the hosting backup process.');setMessage('Preparing your backup ZIP…');const blob=await backupZip([{name:'manifest.json',data:metadata},...entries]);if(blob.size>backupLimit)throw Error('Backup exceeds 200 MB. Use the hosting backup process.');downloadBlob(blob,'Client-Dashboard-Full-Backup-'+new Date().toISOString().slice(0,10)+'.zip');setMessage('Backup download started. Keep the ZIP private and check that your browser saved it.');toast.success('Full backup download started')
 }catch(e){setError((e as Error).message);setMessage('')}finally{setBusy(false)}}
 async function cancel(){if(!preview)return;const response=await fetch('/api/recovery',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({session:preview.session})});if(!response.ok)throw Error('Could not cancel the staged restore. Please retry.');setPreview(null);setZip(null);setConfirmed(false)}
 async function choose(file?:File){if(!file)return;setBusy(true);setError('');setMessage('Checking backup…');setConfirmed(false);try{if(preview)await cancel();const archive=await readBackupZip(file),names=new Set(archive.names),expected=['manifest.json',...(archive.manifest.files||[]).map((f:any)=>'files/'+f.id)];if(names.size!==expected.length||expected.some(name=>!names.has(name)))throw Error('Backup files do not match its manifest.');for(const f of archive.manifest.files||[]){setMessage('Checking '+f.id);const blob=await archive.entry('files/'+f.id);if(blob.size!==f.size||await sha256(blob)!==f.sha256)throw Error('A file checksum failed. Use another backup.');}const response=await fetch('/api/recovery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'preview',backup:archive.manifest})}),data:any=await response.json();if(!response.ok)throw Error(data.error);setPreview(data);setZip(archive);setMessage('Preview ready. Nothing has been restored yet.')}catch(e){setError((e as Error).message);setMessage('')}finally{setBusy(false)}}
 async function restore(){if(!preview||!zip)return;setBusy(true);setError('');try{for(const [index,f] of preview.files.entries()){setMessage('Restoring file '+(index+1)+' of '+preview.files.length);const blob=await zip.entry('files/'+f.id),response=await fetch('/api/recovery/files?'+new URLSearchParams({session:preview.session,id:f.id}),{method:'PUT',headers:{'Content-Type':'application/octet-stream'},body:blob}),data:any=await response.json();if(!response.ok)throw Error(data.error)}setMessage('Saving restored records…');const response=await fetch('/api/recovery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'commit',session:preview.session})}),data:any=await response.json();if(!response.ok)throw Error(data.error);setPreview(null);setZip(null);setConfirmed(false);setMessage(data.restored+' missing records restored. Existing work was kept.');await onChanged();await trash();toast.success('Backup restored')}catch(e){setError((e as Error).message);setMessage('Restore paused. Retry to continue, or Cancel preview to clean up files not used by saved records.')}finally{setBusy(false)}}
 async function restoreItem(item:any){setBusy(true);setError('');try{const response=await fetch('/api/trash',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id})}),d:any=await response.json();if(!response.ok)throw Error(d.error);await onChanged();await trash();toast.success('Restored from Trash')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function purge(item:any){if(!confirm('Permanently delete '+(item.record.name||item.record.title)+'? Its stored file, if any, will also be removed. This cannot be undone.'))return;setBusy(true);setError('');try{const response=await fetch('/api/trash',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id})}),d:any=await response.json();if(!response.ok)throw Error(d.error);await trash();toast.success('Permanently deleted')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><div className="recovery-grid"><section className="panel recovery-card"><h3>Full workspace backup</h3><a className="resource-link" href="/downloads/RELEASE-v3.6.md" download>Download recovery instructions and limits</a><p>Download current records and uploaded files together in one ZIP. Passwords, API keys and Trash are not included.</p><button className="primary" disabled={busy||!!preview} onClick={exportBackup}>Download full backup</button><p className="subtle">Browser backup limit: 200 MB total, 8 MB records, 20 MB per uploaded file. Large workspaces need the hosting backup process. Keep downloaded backups private.</p></section><section className="panel recovery-card"><h3>Restore missing records</h3><p>Upload an unmodified full backup ZIP made by this dashboard. Preview first, then restore missing records and files. Current records, edits and settings stay as they are.</p><label className="secondary upload">Choose backup ZIP<input type="file" accept=".zip,application/zip" disabled={busy} onChange={e=>{choose(e.target.files?.[0]);e.target.value=''}}/></label><p className="subtle">To roll back edits or recover a whole deployment, restore into a fresh workspace. A records-only JSON export does not contain files and is not accepted here.</p>{preview&&<div className="restore-preview"><strong>{preview.newRecords} missing records · {preview.files.length} files</strong><p>{preview.kept} existing records will be kept. Preview expires after one hour.</p><label className="checkbox-label"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I checked this backup and want to restore the missing records.</label><div className="social-actions"><button className="primary" disabled={busy||!confirmed||!preview.newRecords} onClick={restore}>Restore backup</button><button className="secondary" disabled={busy} onClick={async()=>{try{await cancel();setMessage('Restore preview cancelled.')}catch(e){setError((e as Error).message)}}}>Cancel preview</button></div></div>}</section></div>{message&&<p role="status" className="info-note">{message}</p>}{error&&<p role="alert" className="import-errors">{error}</p>}<section className="panel recovery-card"><h3>Trash · {items.length} items</h3><p>Deleted records and their uploaded files stay here until you permanently remove them. Restore the client or project before its dependent records. Available resource and task links are restored without replacing newer edits.</p>{items.length?<div className="trash-list">{items.map(item=><article key={item.id}><div><strong>{item.record.name||item.record.title||item.record.id}</strong><small>{item.record.kind} · Deleted {new Date(item.deletedAt).toLocaleString()}</small></div><button className="secondary" disabled={busy} onClick={()=>restoreItem(item)}>Restore</button><button className="danger" disabled={busy} onClick={()=>purge(item)}>Delete permanently</button></article>)}</div>:<p className="subtle">Trash is empty.</p>}</section></>;
}
