import {invoiceLines,invoiceTotals} from './invoicing';
export async function invoicePdf(r:any,settings:any,client:any){
 const {PDFDocument,StandardFonts,rgb}=await import('../vendor/pdf-lib/index.js');
 const doc=await PDFDocument.create(),font=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold);
 let page:any,y=0;const ink=rgb(.09,.14,.22),muted=rgb(.38,.43,.50);
 function next(){page=doc.addPage([595.28,841.89]);y=790;}
 function text(value:string,size=11,strong=false,color=ink){const f=strong?bold:font;value=String(value||'').replace(/\t/g,' ');for(const paragraph of value.split('\n')){let line='';for(const original of paragraph.split(' ')){const parts:string[]=[];let part='';for(const char of original){try{if(f.widthOfTextAtSize(part+char,size)>490&&part){parts.push(part);part=char}else part+=char}catch{throw Error('This name or note uses characters unavailable in the PDF font. Use Print / Save as PDF for this invoice.')}}parts.push(part);for(const word of parts){const test=line?line+' '+word:word;let width:number;try{width=f.widthOfTextAtSize(test,size)}catch{throw Error('This name or note uses characters unavailable in the PDF font. Use Print / Save as PDF for this invoice.')}if(width>490&&line){draw(line);line=word}else line=test;}}draw(line);}function draw(line:string){if(y<70)next();page.drawText(line,{x:48,y,size,font:f,color});y-=size+7;}}
 const snapshot=r.billingSnapshot,b=snapshot?.business||{name:settings.name,email:settings.businessEmail,address:settings.businessAddress,logo:settings.logo},c=snapshot?.client||{name:client?.name,email:client?.email,address:client?.billingAddress,logo:client?.logo};
 next();for(const [identity,x] of [[b,48],[c,480]] as any){if(identity.logo){const image=identity.logo.startsWith('data:image/png')?await doc.embedPng(identity.logo):await doc.embedJpg(identity.logo);const scale=Math.min(60/image.width,50/image.height);page.drawImage(image,{x,y:744,width:image.width*scale,height:image.height*scale})}}if(b.logo||c.logo)y=718;
 text(b.name,17,true);text(b.email||'',10,false,muted);text(b.address||'',10,false,muted);y-=15;text('INVOICE',22,true);text(r.invoiceNumber||'Legacy invoice',12,true);text(r.title,12);text('Issued: '+(r.issuedDate||'Not recorded')+'     Due: '+r.date,10,false,muted);text('Status: '+r.status,10);y-=12;text('Bill to',10,true,muted);text(c.name,13,true);text(c.email||'',10);text(c.address||'',10);y-=16;
 text('Description / quantity / unit price / total',11,true);
 const currency=r.currency,fmt=(n:number)=>currency+' '+Number(n).toLocaleString('en',{minimumFractionDigits:2,maximumFractionDigits:2});
 for(const l of invoiceLines(r)){let height=250;try{height=l.description.split('\n').reduce((sum,p)=>sum+Math.max(1,Math.ceil(bold.widthOfTextAtSize(p,11)/440))*18,0)+25}catch{}if(y<70+height)next();text(l.description,11,true);text(l.quantity+' x '+fmt(l.rate)+' = '+fmt(Math.round(l.quantity*l.rate*100)/100),10,false,muted);y-=4;}
 const t=invoiceTotals(invoiceLines(r),r.discount||0,r.taxRate||0);if(y<245)next();y-=12;
 for(const [label,value] of [['Subtotal',t.subtotal],['Discount',t.discount],['Tax ('+(r.taxRate||0)+'%)',t.tax],['Total',r.amount],['Paid',r.paid],['Balance',Math.max(0,r.amount-r.paid)]])text(label+': '+fmt(Number(value)),12,['Total','Balance'].includes(String(label)));
 if(r.terms){y-=12;text('Payment instructions',11,true);text(r.terms,10)}if(r.notes){y-=12;text('Notes',11,true);text(r.notes,10)}
 const pages=doc.getPages();pages.forEach((p:any,i:number)=>p.drawText((r.invoiceNumber||'Invoice')+'  /  '+(i+1)+' of '+pages.length,{x:48,y:35,size:9,font,color:muted}));return new Uint8Array(await doc.save());
}
export function downloadFile(bytes:BlobPart,name:string,type:string){const url=URL.createObjectURL(new Blob([bytes],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
export function printInvoice(r:any,settings:any,client:any){
 const win=window.open('','_blank');if(!win)throw Error('Allow pop-ups to print this invoice.');
 const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
 const b=r.billingSnapshot?.business||{name:settings.name,email:settings.businessEmail,address:settings.businessAddress,logo:settings.logo},c=r.billingSnapshot?.client||{name:client?.name,email:client?.email,address:client?.billingAddress,logo:client?.logo};
 const money=(n:number)=>esc(r.currency+' '+Number(n||0).toFixed(2)),t=invoiceTotals(invoiceLines(r),r.discount||0,r.taxRate||0);
 win.document.write('<!doctype html><html><head><title>'+esc(r.invoiceNumber||r.title)+'</title><style>body{font:14px Arial;color:#172238;margin:40px}img{width:65px;height:55px;object-fit:contain}header{display:flex;justify-content:space-between}p{white-space:pre-wrap}table{width:100%;border-collapse:collapse}th,td{padding:12px;text-align:left;border-bottom:1px solid #ddd}th{background:#f2f5f8}.totals{text-align:right;line-height:1.8}@media print{button{display:none}thead{display:table-header-group}tr{break-inside:avoid}}</style></head><body><button onclick="window.print()">Print / Save as PDF</button><header><div>'+(b.logo?'<img src="'+esc(b.logo)+'" alt="Business logo">':'')+'<h2>'+esc(b.name)+'</h2><p>'+esc(b.email)+'\n'+esc(b.address)+'</p></div><div>'+(c.logo?'<img src="'+esc(c.logo)+'" alt="Client logo">':'')+'</div></header><h1>INVOICE '+esc(r.invoiceNumber||'')+'</h1><p>'+esc(r.title)+'<br>Issued: '+esc(r.issuedDate||'Not recorded')+' · Due: '+esc(r.date)+' · '+esc(r.status)+'</p><h3>Bill to</h3><p>'+esc(c.name)+'\n'+esc(c.email)+'\n'+esc(c.address)+'</p><table><thead><tr><th>Description</th><th>Quantity</th><th>Rate</th><th>Total</th></tr></thead><tbody>'+invoiceLines(r).map(l=>'<tr><td>'+esc(l.description)+'</td><td>'+l.quantity+'</td><td>'+money(l.rate)+'</td><td>'+money(Math.round(l.quantity*l.rate*100)/100)+'</td></tr>').join('')+'</tbody></table><p class="totals">Subtotal: '+money(t.subtotal)+'<br>Discount: '+money(t.discount)+'<br>Tax ('+(r.taxRate||0)+'%): '+money(t.tax)+'<br><b>Total: '+money(r.amount)+'</b><br>Paid: '+money(r.paid)+'<br><b>Balance: '+money(Math.max(0,r.amount-r.paid))+'</b></p><h3>Payment instructions</h3><p>'+esc(r.terms)+'</p><p>'+esc(r.notes)+'</p></body></html>');win.document.close();
}
