import {extractPostId} from './social';
export const reportMetrics=['views','likes','comments','shares','clicks','impressions','reach','saves','reactions','pinClicks'];
export function parseReportCSV(text:string){
 if(text.length>2*1024*1024)throw Error('Use a report under 2 MB.');text=text.replace(/^\uFEFF/,'');const first=text.split(/\r?\n/)[0],separator=first.includes('\t')?'\t':',';const rows:string[][]=[];let row:string[]=[],field='',quoted=false;
 for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++}else if(!field||quoted)quoted=!quoted;else field+=c}else if(c===separator&&!quoted){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(x=>x.trim()))rows.push(row);row=[];field=''}else field+=c;if(rows.length>2000||row.length>100)throw Error('Use up to 2,000 rows and 100 columns.');}
 if(quoted)throw Error('A quoted CSV field is unfinished.');row.push(field);if(row.some(x=>x.trim()))rows.push(row);return rows;
}
function normalizedURL(value:string){try{const u=new URL(value);u.hostname=u.hostname.replace(/^www\./,'');u.hash='';if(!['youtube.com','youtu.be','m.youtube.com'].includes(u.hostname))u.search='';u.pathname=u.pathname.replace(/\/$/,'');return u.href}catch{return value.trim()}}
export function postKeys(platform:string,value:string){const keys=[value.trim(),normalizedURL(value)];try{const id=extractPostId(platform,value);if(id)keys.push(id,platform==='Facebook'?id.split('_').at(-1)!:id)}catch{}return [...new Set(keys.filter(Boolean))]}
export function matchReportPost(records:any[],account:any,ref:string){
 const wanted=new Set(postKeys(account.platform,ref));return records.filter(r=>r.kind==='content'&&r.client===account.client&&r.socialAccountId===account.id&&r.platform===account.platform&&r.status==='Published'&&[...postKeys(account.platform,r.postRef||''),r.metricsPostId||''].some(k=>k&&wanted.has(k)));
}
export function parseMetricCell(value:string,key:string,platform:string){const cleaned=value.trim().replace(/,/g,'');if(!cleaned)return null;if(!/^-?\d+(\.\d+)?$/.test(cleaned)||!Number.isFinite(Number(cleaned))||Math.abs(Number(cleaned))>1e15||Number(cleaned)<0&&!(platform==='LinkedIn'&&key==='likes'))throw Error('Use full numeric counts, not percentages or values such as 1.2K.');return Number(cleaned)}
export function guessColumn(headers:string[],key:string){const names:Record<string,string[]>={post:['posturl','postlink','permalink','videolink','videourl','url','pinurl','postid','videoid','pinid','id'],views:['views','videoviews','viewcount'],likes:['likes','likecount'],comments:['comments','commentcount'],shares:['shares','sharecount'],clicks:['outboundclicks','linkclicks','clicks','clickcount'],impressions:['impressions','impressioncount'],reach:['reach'],saves:['saves','savecount'],reactions:['reactions','totalreactions'],pinClicks:['pinclicks']};return headers.findIndex(h=>(names[key]||[]).includes(h.toLowerCase().replace(/[^a-z0-9]/g,'')))}
