// Browser-only reader for the simple monthly .xlsx template. Never evaluates formulas or macros.
export async function readPlanWorkbook(file:File){
 if(!file.name.toLowerCase().endsWith('.xlsx')||file.size>2*1024*1024)throw Error('Choose an .xlsx workbook under 2 MB.');
 const bytes=new Uint8Array(await file.arrayBuffer()),view=new DataView(bytes.buffer);let end=-1;
 for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(view.getUint32(i,true)===0x06054b50){end=i;break}
 if(end<0||view.getUint16(end+4,true)!==0||view.getUint16(end+6,true)!==0)throw Error('This is not a readable Excel workbook.');
 const count=view.getUint16(end+10,true);if(count>200)throw Error('Use the simple monthly template workbook.');
 let offset=view.getUint32(end+16,true),total=0;const entries=new Map<string,{offset:number;size:number;length:number;method:number}>();
 for(let n=0;n<count;n++){if(offset+46>bytes.length||view.getUint32(offset,true)!==0x02014b50)throw Error('Workbook directory is damaged.');const flags=view.getUint16(offset+8,true),method=view.getUint16(offset+10,true),size=view.getUint32(offset+20,true),length=view.getUint32(offset+24,true),namesize=view.getUint16(offset+28,true),extra=view.getUint16(offset+30,true),comment=view.getUint16(offset+32,true),local=view.getUint32(offset+42,true);total+=length;if(flags&1||total>10*1024*1024||![0,8].includes(method))throw Error('Workbook is encrypted or too large.');const name=new TextDecoder().decode(bytes.slice(offset+46,offset+46+namesize));entries.set(name,{offset:local,size,length,method});offset+=46+namesize+extra+comment;}
 async function xml(name:string){const e=entries.get(name);if(!e)return null;if(e.offset+30>bytes.length||view.getUint32(e.offset,true)!==0x04034b50)throw Error('Workbook entry is damaged.');const start=e.offset+30+view.getUint16(e.offset+26,true)+view.getUint16(e.offset+28,true);if(start+e.size>bytes.length)throw Error('Workbook entry is incomplete.');const input=bytes.slice(start,start+e.size);let output=input;if(e.method===8){const stream=new Blob([input]).stream().pipeThrough(new DecompressionStream('deflate-raw'));const reader=stream.getReader(),chunks:Uint8Array[]= [];let length=0;while(true){const item=await reader.read();if(item.done)break;length+=item.value.length;if(length>e.length||length>10*1024*1024){await reader.cancel();throw Error('Workbook expands beyond its declared size.')}chunks.push(item.value)}output=new Uint8Array(length);let at=0;for(const chunk of chunks){output.set(chunk,at);at+=chunk.length}}if(output.length!==e.length)throw Error('Workbook entry length does not match.');const doc=new DOMParser().parseFromString(new TextDecoder().decode(output),'application/xml');if(doc.querySelector('parsererror'))throw Error('Workbook XML is damaged.');return doc}
 const strings=await xml('xl/sharedStrings.xml'),shared=strings?Array.from(strings.getElementsByTagName('si')).map(s=>Array.from(s.getElementsByTagName('t')).map(t=>t.textContent||'').join('')):[];
 const workbook=await xml('xl/workbook.xml'),rels=await xml('xl/_rels/workbook.xml.rels');const sheet=Array.from(workbook?.getElementsByTagName('sheet')||[]).find(s=>s.getAttribute('name')==='Plan');if(!sheet)throw Error('Keep the worksheet named Plan.');const rel=Array.from(rels?.getElementsByTagName('Relationship')||[]).find(r=>r.getAttribute('Id')===sheet.getAttribute('r:id'));const target=rel?.getAttribute('Target');if(!target||target.includes('..'))throw Error('Plan worksheet link is invalid.');const doc=await xml(target.startsWith('/')?target.slice(1):'xl/'+target);if(!doc)throw Error('Plan worksheet is missing.');
 const rows=Array.from(doc.getElementsByTagName('row'));if(rows.length>400)throw Error('Import up to 366 plan rows at a time.');return rows.map(row=>{const out:string[]=[];for(const cell of Array.from(row.getElementsByTagName('c'))){const ref=cell.getAttribute('r')||'',column=ref.match(/^[A-Z]+/)?.[0]||'';let index=0;for(const char of column)index=index*26+char.charCodeAt(0)-64;const type=cell.getAttribute('t'),raw=cell.getElementsByTagName('v')[0]?.textContent||'';let value=type==='s'?shared[Number(raw)]||'':type==='inlineStr'?Array.from(cell.getElementsByTagName('t')).map(t=>t.textContent||'').join(''):raw;if(index===1&&value&&type!=='s'&&type!=='inlineStr'&&type!=='str'&&type!=='d'){const serial=Number(value);if(Number.isFinite(serial)&&serial>0){const epoch=workbook?.getElementsByTagName('workbookPr')[0]?.getAttribute('date1904');value=new Date(Date.UTC(epoch==='1'||epoch==='true'?1904:1899,epoch==='1'||epoch==='true'?0:11,epoch==='1'||epoch==='true'?1:30)+Math.round(serial)*86400000).toISOString().slice(0,10)}}out[index-1]=value;}return {row:Number(row.getAttribute('r')),values:out}});
}
