import {database,bucket} from '@/db/raw';
import {sample,statuses,platforms} from '@/lib/sample';
import {validFormat,normalizeFormat} from '@/lib/content-types';
import {validPlatform} from '@/lib/social';
export async function GET(){try{const db=database();await db.batch([...sample.map(r=>db.prepare("INSERT OR IGNORE INTO records (id,kind,client,payload) SELECT ?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM records WHERE id='initialized')").bind(r.id,r.kind,r.client,JSON.stringify(r))),db.prepare("INSERT OR IGNORE INTO records VALUES ('initialized','meta','','{}')")]);const rows=await db.prepare("SELECT payload FROM records WHERE kind != 'meta'").all();return Response.json({records:rows.results.map((r:any)=>JSON.parse(r.payload))});}catch(e){console.error(e);return Response.json({error:'Your workspace could not be loaded. Please try again.'},{status:503});}}
export async function POST(req:Request){try{const r:any=await req.json();if(!r||typeof r!=='object')return Response.json({error:'Invalid record'},{status:400});if(!['client','content','resource'].includes(r.kind)||typeof r.id!=='string'||r.id.length>100||(r.id==='initialized'||r.id.startsWith('invoice-counter-'))||typeof r.client!=='string')return Response.json({error:'Invalid record.'},{status:400});if(r.kind==='content'&&(!r.title?.trim()||!statuses.includes(r.status)||!validPlatform(r.platform)||!validFormat(r.format)||!/^\d{4}-\d{2}-\d{2}$/.test(r.date)))return Response.json({error:'Check the content title, date, format and status.'},{status:400});if(r.kind==='content')r.format=normalizeFormat(r.format);if(r.kind==='client'&&!r.name?.trim())return Response.json({error:'Client name is required.'},{status:400});if(r.kind==='resource'&&(!r.name?.trim()||!/^https?:\/\//i.test(r.url)))return Response.json({error:'Use a full https:// or http:// resource link.'},{status:400});for(const k of ['views','likes','comments','shares','clicks',...(r.leads!==undefined?['leads']:[]),...(r.conversions!==undefined?['conversions']:[])])if(r.kind==='content'&&(!Number.isFinite(r[k])||r[k]<0))return Response.json({error:'Metrics must be non-negative numbers.'},{status:400});if(r.kind==='client'&&r.logo&&(!/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/]+=*$/.test(r.logo)||r.logo.length>200000))return Response.json({error:'Use a valid PNG or JPG logo.'},{status:400});if(JSON.stringify(r).length>(r.kind==='client'?250000:50000))return Response.json({error:'This record is too large.'},{status:400});const db=database();const existing:any=await db.prepare('SELECT kind,client,payload FROM records WHERE id=?').bind(r.id).first();if(existing&&(existing.kind!==r.kind||existing.client!==r.client))return Response.json({error:'Record identity cannot be changed.'},{status:400});if(r.kind!=='client'&&!(await db.prepare("SELECT id FROM records WHERE id=? AND kind='client'").bind(r.client).first()))return Response.json({error:'Client not found.'},{status:400});if(r.kind==='content'&&r.projectId&&!(await db.prepare("SELECT id FROM records WHERE id=? AND kind='project' AND client=?").bind(r.projectId,r.client).first()))return Response.json({error:'The linked project must belong to this client.'},{status:400});if(r.kind==='content'){
 const prior=existing?JSON.parse(existing.payload):null;
 r.platform=r.platform.trim();r.socialAccountId=typeof r.socialAccountId==='string'?r.socialAccountId:'';r.postRef=typeof r.postRef==='string'?r.postRef.trim():'';
 if(r.postRef.length>2000||/[\x00-\x1f\x7f]/.test(r.postRef)||r.postRef&&!/^https:\/\/|^[-\w:]+$/.test(r.postRef))return Response.json({error:'Use a full https:// post link or its exact API post ID.'},{status:400});
 for(const key of ['metricsSource','syncedMetrics','metricsPostId','metricsPeriod','metricsSyncedAt'])delete r[key];
 if(r.socialAccountId){const a:any=await db.prepare("SELECT payload FROM records WHERE id=? AND kind='social-account' AND client=?").bind(r.socialAccountId,r.client).first();if(!a||JSON.parse(a.payload).platform!==r.platform)return Response.json({error:'Choose an account belonging to this client and channel.'},{status:400});r.metricsSource='api';r.syncedMetrics={};
  if(prior?.socialAccountId===r.socialAccountId&&prior?.postRef===r.postRef&&prior?.platform===r.platform)for(const key of ['syncedMetrics','metricsPostId','metricsPeriod','metricsSyncedAt'])if(prior[key]!==undefined)r[key]=prior[key];
 }
}
await db.prepare('INSERT INTO records (id,kind,client,payload) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,client=excluded.client,payload=excluded.payload').bind(r.id,r.kind,r.client,JSON.stringify(r)).run();return Response.json({record:r});}catch(e){console.error(e);return Response.json({error:'Could not save. Your changes are still here; please retry.'},{status:503});}}
export async function DELETE(req:Request){try{const {id}=await req.json() as {id:string};const db=database();const r:any=await db.prepare('SELECT payload FROM records WHERE id=?').bind(id).first();if(!r)return Response.json({error:'Record not found'},{status:404});if(!['content','resource'].includes(JSON.parse(r.payload).kind))return Response.json({error:'Clients cannot be deleted.'},{status:400});const record=JSON.parse(r.payload);const statements=[];if(record.kind==='content'){const linked=await db.prepare("SELECT id,payload FROM records WHERE kind='task' AND client=?").bind(record.client).all();for(const item of linked.results as any[]){const t=JSON.parse(item.payload);if(t.contentId===id){t.contentId='';statements.push(db.prepare('UPDATE records SET payload=? WHERE id=?').bind(JSON.stringify(t),item.id));}}}if(record.kind==='resource'){const linked=await db.prepare("SELECT id,payload FROM records WHERE kind='content' AND client=?").bind(record.client).all();for(const item of linked.results as any[]){const c=JSON.parse(item.payload);if(c.resourceIds?.includes(id)){c.resourceIds=c.resourceIds.filter((v:string)=>v!==id);statements.push(db.prepare('UPDATE records SET payload=? WHERE id=?').bind(JSON.stringify(c),item.id));}}}statements.push(db.prepare('DELETE FROM records WHERE id=?').bind(id));await db.batch(statements);if(record.kind==='resource'&&record.type==='File'){try{await bucket().delete(id)}catch(e){console.error('File cleanup failed',e)}}return Response.json({ok:true});}catch(e){console.error(e);return Response.json({error:'Could not delete. Please retry.'},{status:503});}}
